//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaeCoach.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Responses = new HashSet<Response>();
        }
    
        public int PostID { get; set; }
        public string PostText { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<int> Topic { get; set; }
    
        public virtual myUser myUser { get; set; }
        public virtual Topic Topic1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response> Responses { get; set; }

        public static List<Response> listResponses { get; set; }

        public List<string> GetResponses(int topicID, int postID)
        {
            string myRespons = "No Respons Yet";
            BaeCoachEntities3 db = new BaeCoachEntities3();
            List<string> getResponse = db.Responses.Where(z => Topic == topicID && z.FK_PostID == PostID).Select(o=>o.RespronsText).ToList();

            return getResponse;
            //    RespronsText = x.RespronsText
            //}).FirstOrDefault();
            //listResponses = db.Responses.Where(z => Topic == topicID && z.FK_PostID == PostID).ToList();
            //return listResponses.Select(x=> new Response { 
            //    RespronsText = x.RespronsText
            //    });
            //}
        }
    }
}
