//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaeCoach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profession
    {
        public int ProfessionID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> CoachID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> VerificationID { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual University University { get; set; }
        public virtual Verification Verification { get; set; }
    }
}
